-- Vehicle 360 Full Metadata Bootstrap v0.2
DELETE FROM vehicle360.control.pipeline_parameter WHERE pipeline_id LIKE 'PL_SILVER_%' OR pipeline_id LIKE 'PL_GOLD_%';
DELETE FROM vehicle360.control.pipeline_dependency WHERE parent_pipeline_id LIKE 'PL_SILVER_%' OR parent_pipeline_id LIKE 'PL_GOLD_%' OR child_pipeline_id LIKE 'PL_SILVER_%' OR child_pipeline_id LIKE 'PL_GOLD_%';
DELETE FROM vehicle360.control.data_quality_rule WHERE pipeline_id LIKE 'PL_SILVER_%' OR pipeline_id LIKE 'PL_GOLD_%';
DELETE FROM vehicle360.control.pipeline_watermark WHERE pipeline_id LIKE 'PL_SILVER_%' OR pipeline_id LIKE 'PL_GOLD_%';
DELETE FROM vehicle360.control.pipeline_config WHERE pipeline_id LIKE 'PL_SILVER_%' OR pipeline_id LIKE 'PL_GOLD_%';

INSERT INTO vehicle360.control.pipeline_config (
pipeline_id,pipeline_name,pipeline_group,source_catalog,source_schema,source_object,source_type,target_catalog,target_schema,target_object,
load_type,transformation_mode,processing_notebook,custom_transform_notebook,audit_enabled,primary_key_columns,sequence_column,watermark_column,merge_condition,
execution_order,retry_count,timeout_minutes,is_active,created_by,created_timestamp,updated_by,updated_timestamp
)
VALUES
('PL_SILVER_VEHICLE_MODEL','Silver Vehicle Model Load','SILVER','vehicle360','bronze','vehicle_model','TABLE','vehicle360','silver','vehicle_model','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'model_id',NULL,'ingestion_timestamp',NULL,10,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_SILVER_DEALER','Silver Dealer Load','SILVER','vehicle360','bronze','dealer','TABLE','vehicle360','silver','dealer','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'dealer_id',NULL,'ingestion_timestamp',NULL,20,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_SILVER_CUSTOMER','Silver Customer Load','SILVER','vehicle360','bronze','customer','TABLE','vehicle360','silver','customer','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'customer_id',NULL,'ingestion_timestamp',NULL,30,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_SILVER_VEHICLE','Silver Vehicle Load','SILVER','vehicle360','bronze','vehicle','TABLE','vehicle360','silver','vehicle','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'vin',NULL,'ingestion_timestamp',NULL,40,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_SILVER_PART','Silver Part Load','SILVER','vehicle360','bronze','part_master','TABLE','vehicle360','silver','part','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'part_id',NULL,'ingestion_timestamp',NULL,50,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_SILVER_FAILURE_CODE','Silver Failure Code Load','SILVER','vehicle360','bronze','failure_code','TABLE','vehicle360','silver','failure_code','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'failure_code',NULL,'ingestion_timestamp',NULL,60,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_SILVER_SERVICE_ORDER','Silver Service Order Load','SILVER','vehicle360','bronze','service_order','TABLE','vehicle360','silver','service_order','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'service_order_id',NULL,'ingestion_timestamp',NULL,70,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_SILVER_REPAIR_JOB','Silver Repair Job Load','SILVER','vehicle360','bronze','repair_job','TABLE','vehicle360','silver','repair_job','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'repair_job_id',NULL,'ingestion_timestamp',NULL,80,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_SILVER_PART_CONSUMPTION','Silver Part Consumption Load','SILVER','vehicle360','bronze','part_consumption','TABLE','vehicle360','silver','part_consumption','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'part_consumption_id',NULL,'ingestion_timestamp',NULL,90,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_SILVER_WARRANTY_CLAIM','Silver Warranty Claim Load','SILVER','vehicle360','bronze','warranty_claim','TABLE','vehicle360','silver','warranty_claim','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'warranty_claim_id',NULL,'ingestion_timestamp',NULL,100,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_SILVER_VEHICLE_USAGE','Silver Vehicle Usage Load','SILVER','vehicle360','bronze','vehicle_daily_usage','TABLE','vehicle360','silver','vehicle_daily_usage','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'usage_id',NULL,'ingestion_timestamp',NULL,110,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_SILVER_BREAKDOWN','Silver Breakdown Load','SILVER','vehicle360','bronze','breakdown','TABLE','vehicle360','silver','breakdown','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'breakdown_id',NULL,'ingestion_timestamp',NULL,120,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_GOLD_DIM_DATE','Gold Date Dimension','GOLD','vehicle360','silver','vehicle_daily_usage','TABLE','vehicle360','gold','dim_date','FULL','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'date_key',NULL,'ingestion_timestamp',NULL,10,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_GOLD_DIM_VEHICLE_MODEL','Gold Vehicle Model Dimension','GOLD','vehicle360','silver','vehicle_model','TABLE','vehicle360','gold','dim_vehicle_model','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'vehicle_model_key',NULL,'ingestion_timestamp',NULL,20,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_GOLD_DIM_CUSTOMER','Gold Customer Dimension','GOLD','vehicle360','silver','customer','TABLE','vehicle360','gold','dim_customer','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'customer_key',NULL,'ingestion_timestamp',NULL,30,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_GOLD_DIM_DEALER','Gold Dealer Dimension','GOLD','vehicle360','silver','dealer','TABLE','vehicle360','gold','dim_dealer','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'dealer_key',NULL,'ingestion_timestamp',NULL,40,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_GOLD_DIM_PART','Gold Part Dimension','GOLD','vehicle360','silver','part','TABLE','vehicle360','gold','dim_part','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'part_key',NULL,'ingestion_timestamp',NULL,50,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_GOLD_DIM_FAILURE_CODE','Gold Failure Code Dimension','GOLD','vehicle360','silver','failure_code','TABLE','vehicle360','gold','dim_failure_code','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'failure_code_key',NULL,'ingestion_timestamp',NULL,60,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_GOLD_DIM_VEHICLE','Gold Vehicle Dimension','GOLD','vehicle360','silver','vehicle','TABLE','vehicle360','gold','dim_vehicle','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'vehicle_key',NULL,'ingestion_timestamp',NULL,70,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_GOLD_FACT_SERVICE_ORDER','Gold Service Order Fact','GOLD','vehicle360','silver','service_order','TABLE','vehicle360','gold','fact_service_order','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'service_order_key',NULL,'ingestion_timestamp',NULL,100,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_GOLD_FACT_REPAIR_JOB','Gold Repair Job Fact','GOLD','vehicle360','silver','repair_job','TABLE','vehicle360','gold','fact_repair_job','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'repair_job_key',NULL,'ingestion_timestamp',NULL,110,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_GOLD_FACT_PART_CONSUMPTION','Gold Part Consumption Fact','GOLD','vehicle360','silver','part_consumption','TABLE','vehicle360','gold','fact_part_consumption','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'part_consumption_key',NULL,'ingestion_timestamp',NULL,120,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_GOLD_FACT_WARRANTY_CLAIM','Gold Warranty Claim Fact','GOLD','vehicle360','silver','warranty_claim','TABLE','vehicle360','gold','fact_warranty_claim','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'warranty_claim_key',NULL,'ingestion_timestamp',NULL,130,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_GOLD_FACT_VEHICLE_DAILY_USAGE','Gold Vehicle Daily Usage Fact','GOLD','vehicle360','silver','vehicle_daily_usage','TABLE','vehicle360','gold','fact_vehicle_daily_usage','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'vehicle_usage_key',NULL,'ingestion_timestamp',NULL,140,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('PL_GOLD_FACT_BREAKDOWN','Gold Breakdown Fact','GOLD','vehicle360','silver','breakdown','TABLE','vehicle360','gold','fact_breakdown','MERGE','NOTEBOOK','/Workspace/Vehicle360/vehicle360_medallion_project/scripts/databricks_workflows/run_pipeline_task.py',NULL,true,'breakdown_key',NULL,'ingestion_timestamp',NULL,150,1,60,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp());

INSERT INTO vehicle360.control.data_quality_rule (
rule_id,pipeline_id,rule_name,rule_description,rule_type,column_name,rule_expression,reference_object,reference_column,severity,failure_action,threshold_value,is_active,created_by,created_timestamp,updated_by,updated_timestamp
)
VALUES
('DQ_SILVER_VEHICLE_VIN_NOT_NULL','PL_SILVER_VEHICLE','VIN is not null','Vehicle VIN must not be null','NOT_NULL','vin','vin IS NOT NULL',NULL,NULL,'CRITICAL','FAIL_PIPELINE',0,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('DQ_SILVER_SERVICE_ORDER_ID_NOT_NULL','PL_SILVER_SERVICE_ORDER','Service order ID is not null','Service order ID must not be null','NOT_NULL','service_order_id','service_order_id IS NOT NULL',NULL,NULL,'CRITICAL','FAIL_PIPELINE',0,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('DQ_SILVER_REPAIR_JOB_ID_NOT_NULL','PL_SILVER_REPAIR_JOB','Repair job ID is not null','Repair job ID must not be null','NOT_NULL','repair_job_id','repair_job_id IS NOT NULL',NULL,NULL,'CRITICAL','FAIL_PIPELINE',0,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('DQ_SILVER_PART_CONSUMPTION_ID_NOT_NULL','PL_SILVER_PART_CONSUMPTION','Part consumption ID is not null','Part consumption ID must not be null','NOT_NULL','part_consumption_id','part_consumption_id IS NOT NULL',NULL,NULL,'CRITICAL','FAIL_PIPELINE',0,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('DQ_SILVER_WARRANTY_CLAIM_ID_NOT_NULL','PL_SILVER_WARRANTY_CLAIM','Warranty claim ID is not null','Warranty claim ID must not be null','NOT_NULL','warranty_claim_id','warranty_claim_id IS NOT NULL',NULL,NULL,'CRITICAL','FAIL_PIPELINE',0,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('DQ_SILVER_USAGE_ID_NOT_NULL','PL_SILVER_VEHICLE_USAGE','Usage ID is not null','Usage ID must not be null','NOT_NULL','usage_id','usage_id IS NOT NULL',NULL,NULL,'CRITICAL','FAIL_PIPELINE',0,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp()),
('DQ_SILVER_BREAKDOWN_ID_NOT_NULL','PL_SILVER_BREAKDOWN','Breakdown ID is not null','Breakdown ID must not be null','NOT_NULL','breakdown_id','breakdown_id IS NOT NULL',NULL,NULL,'CRITICAL','FAIL_PIPELINE',0,true,'bootstrap',current_timestamp(),'bootstrap',current_timestamp());

SELECT pipeline_group, COUNT(*) AS pipeline_count
FROM vehicle360.control.pipeline_config
WHERE pipeline_id LIKE 'PL_SILVER_%' OR pipeline_id LIKE 'PL_GOLD_%'
GROUP BY pipeline_group
ORDER BY pipeline_group;
